extends:
  - "@commitlint/config-conventional"

rules:
  scope-case:
    - 2
    - "always"
    - ["lower-case"]
  type-enum:
    - 2
    - "always"
    - [
        "feat",
        "fix",
        "docs",
        "style",
        "refactor",
        "perf",
        "test",
        "build",
        "ci",
        "chore"
      ]
